using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GameCore.Stats.Generator;

[Generator]
public partial class StatsGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat FullyQualifiedNoGlobal = SymbolDisplayFormat.FullyQualifiedFormat
        .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted)
        .WithMemberOptions(SymbolDisplayMemberOptions.IncludeContainingType);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) =>
                {
                    return s is ClassDeclarationSyntax cds
                        && cds.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));
                },
                transform: static (ctx, _) =>
                {
                    var cds = (ClassDeclarationSyntax)ctx.Node;
                    INamedTypeSymbol? symbol = ctx.SemanticModel.GetDeclaredSymbol(cds);
                    return symbol;
                })
            .Where(static x => x is not null)
            .Collect();
        var data = context.CompilationProvider.Combine(classes);
        context.RegisterSourceOutput(data, FindAndGenerate);
    }

    private static void FindAndGenerate(
        SourceProductionContext spc,
        (Compilation Comp, ImmutableArray<INamedTypeSymbol?> Classes) data)
    {
        Compilation compilation = data.Comp;
        ImmutableArray<INamedTypeSymbol?> classes = data.Classes;

        if (classes == null || classes.Length == 0)
            return;

        INamedTypeSymbol? conditionGenericType = compilation.GetTypeByMetadataName("GameCore.Stats.Condition`1");
        INamedTypeSymbol? conditionType = compilation.GetTypeByMetadataName("GameCore.Stats.Condition");

        if (conditionGenericType == null || conditionType == null)
            return;

        List<string> registers = [];

        foreach (INamedTypeSymbol? derivedType in classes)
        {
            if (derivedType == null || derivedType.TypeKind != TypeKind.Class || derivedType.IsAbstract)
                continue;

            bool isMatch = false;
            bool matchedGeneric = false;

            if (SymbolEqualityComparer.Default.Equals(derivedType.BaseType?.OriginalDefinition, conditionGenericType))
            {
                isMatch = true;
                matchedGeneric = true;
            }
            else if (SymbolEqualityComparer.Default.Equals(derivedType.BaseType, conditionType))
            {
                isMatch = true;
            }

            if (!isMatch)
                continue;

            string className = derivedType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            string namespaceName = $"namespace {derivedType.ContainingNamespace?.ToDisplayString()};" ?? "";
            ITypeSymbol? stateType = null;

            if (matchedGeneric && derivedType.BaseType != null && derivedType.BaseType.TypeArguments.Length == 1)
                stateType = derivedType.BaseType.TypeArguments[0];

            string stateTypeText = stateType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? string.Empty;
            string createText = GenerateCreateMethod(namespaceName, className, stateTypeText);
            string fullName = derivedType.ToDisplayString(NullableFlowState.NotNull, FullyQualifiedNoGlobal);
            string hintName = fullName
                // AddSource() doesn't support @ prefix
                .Replace("@", "")
                // AddSource() doesn't support angle brackets
                .Replace("<", "(Of ")
                .Replace(">", ")");

            spc.AddSource(hintName + "_Create.g", SourceText.From(createText, Encoding.UTF8));
            registers.Add(GenerateReadWrite(compilation, fullName, className, stateType));
        }

        string contextText = GenerateContextMethod(registers);
        spc.AddSource("GameCoreStats.GeneratedContext.g", SourceText.From(contextText, Encoding.UTF8));
    }

    private static string GenerateContextMethod(List<string> registers)
    {
        return $$"""
        // <auto-generated>
        using GameCore.Stats;
        using GameCore.Pooling;
        using System.Text.Json;
        using System.Text.Json.Serialization;

        public static class GeneratedConditionRegister
        {
            [System.Runtime.CompilerServices.ModuleInitializer]
            public static void RegisterGeneratedClass()
            {
                {{string.Join("\n", registers)}}
            }
        }
        """;
    }

    private static string GenerateCreateMethod(string namespaceName, string className, string stateName)
    {
        if (stateName.Length == 0)
        {
            return $$"""
            // <auto-generated>
            using GameCore.Stats;

            {{namespaceName}}

            public partial class {{className}}
            {
                public static {{className}} Create() => Create<{{className}}>();
            }
            """;
        }
        else
        {
            return $$"""
            // <auto-generated>
            using GameCore.Stats;

            {{namespaceName}}

            public partial class {{className}}
            {
                public static {{className}} Create({{stateName}} state)
                {
                    var condition = Create<{{className}}>();
                    condition.State = state;
                    return condition;
                }
            }
            """;
        }
    }

    private static string GenerateReadWrite(Compilation comp, string fullCondName, string className, ITypeSymbol? stateType)
    {
        if (stateType is not ITypeSymbol s)
            return "(ref reader, cond) => {}, (writer, cond) => {}";

        INamedTypeSymbol boolSym = comp.GetSpecialType(SpecialType.System_Boolean);
        INamedTypeSymbol stringSym = comp.GetSpecialType(SpecialType.System_String);
        INamedTypeSymbol intSym = comp.GetSpecialType(SpecialType.System_Int32);
        INamedTypeSymbol longSym = comp.GetSpecialType(SpecialType.System_Int64);
        INamedTypeSymbol floatSym = comp.GetSpecialType(SpecialType.System_Single);
        INamedTypeSymbol doubleSym = comp.GetSpecialType(SpecialType.System_Double);
        INamedTypeSymbol decimalSym = comp.GetSpecialType(SpecialType.System_Decimal);
        IEnumerable<IPropertySymbol> props = s.GetMembers().OfType<IPropertySymbol>();
        string stateName = s.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        return $$"""
            GameCore.Stats.ConditionDB.Register<{{fullCondName}}>(
                    "{{className}}",
                    (ref reader, cond) =>
                    {
                        if (reader.TokenType != JsonTokenType.StartObject)
                            throw new JsonException();

                        {{stateName}} state = new();

                        while (reader.Read())
                        {
                            if (reader.TokenType == JsonTokenType.EndObject)
                                break;

                            if (reader.TokenType != JsonTokenType.PropertyName)
                                continue;

                            string stateProp = reader.GetString() ?? string.Empty;
                            reader.Read();

                            switch (stateProp)
                            {{{((Func<string>)(() =>
                                    {
                                        StringBuilder propCases = new();

                                        foreach (IPropertySymbol prop in props)
                                        {
                                            propCases.AppendLine();
                                            propCases.AppendLine($"                        case nameof({stateName}.{prop.Name}):");
                                            ITypeSymbol propType = prop.Type;
                                            propCases.Append($"                            state.{prop.Name} = ");

                                            if (SymbolEqualityComparer.Default.Equals(propType, boolSym))
                                                propCases.AppendLine("reader.GetBoolean();");
                                            else if (SymbolEqualityComparer.Default.Equals(propType, stringSym))
                                                propCases.AppendLine("reader.GetString() ?? string.Empty;");
                                            else if (SymbolEqualityComparer.Default.Equals(propType, intSym))
                                                propCases.AppendLine("reader.GetInt32();");
                                            else if (SymbolEqualityComparer.Default.Equals(propType, longSym))
                                                propCases.AppendLine("reader.GetInt64();");
                                            else if (SymbolEqualityComparer.Default.Equals(propType, floatSym))
                                                propCases.AppendLine("reader.GetSingle();");
                                            else if (SymbolEqualityComparer.Default.Equals(propType, doubleSym))
                                                propCases.AppendLine("reader.GetDouble();");
                                            else if (SymbolEqualityComparer.Default.Equals(propType, decimalSym))
                                                propCases.AppendLine("reader.GetDecimal();");
                                            else if (propType.TypeKind == TypeKind.Enum)
                                            {
                                                string fullPropType = propType.ToDisplayString();
                                                propCases.AppendLine($"Enum.Parse<{fullPropType}>(), reader.GetString() ?? string.Empty;");
                                            }

                                            propCases.Append("                             break;");
                                        }

                                        return propCases.ToString();
                                    }))()}}
                                default:
                                    reader.Skip();
                                    break;
                            }
                        }

                        (({{fullCondName}})cond).State = state;
                    },
                    (Utf8JsonWriter writer, Condition cond) =>
                    {
                        {{stateName}} state = (({{fullCondName}})cond).State;{{((Func<string>)(() =>
                            {
                                StringBuilder propCases = new();
                                propCases.AppendLine();

                                foreach (IPropertySymbol prop in props)
                                {
                                    ITypeSymbol propType = prop.Type;
                                    propCases.Append("                ");

                                    if (SymbolEqualityComparer.Default.Equals(propType, boolSym))
                                        propCases.AppendLine($"writer.WriteBoolean(nameof({stateName}.{prop.Name}), state.{prop.Name});");
                                    else if (SymbolEqualityComparer.Default.Equals(propType, stringSym))
                                        propCases.AppendLine($"writer.WriteString(nameof({stateName}.{prop.Name}), state.{prop.Name});");
                                    else if (SymbolEqualityComparer.Default.Equals(propType, intSym))
                                        propCases.AppendLine($"writer.WriteNumber(nameof({stateName}.{prop.Name}), state.{prop.Name});");
                                    else if (SymbolEqualityComparer.Default.Equals(propType, longSym))
                                        propCases.AppendLine($"writer.WriteNumber(nameof({stateName}.{prop.Name}), state.{prop.Name});");
                                    else if (SymbolEqualityComparer.Default.Equals(propType, floatSym))
                                        propCases.AppendLine($"writer.WriteNumber(nameof({stateName}.{prop.Name}), state.{prop.Name});");
                                    else if (SymbolEqualityComparer.Default.Equals(propType, doubleSym))
                                        propCases.AppendLine($"writer.WriteNumber(nameof({stateName}.{prop.Name}), state.{prop.Name});");
                                    else if (SymbolEqualityComparer.Default.Equals(propType, decimalSym))
                                        propCases.AppendLine($"writer.WriteNumber(nameof({stateName}.{prop.Name}), state.{prop.Name});");
                                    else if (propType.TypeKind == TypeKind.Enum)
                                        propCases.AppendLine($"writer.WriteString(nameof({stateName}.{prop.Name}), state.{prop.Name}.ToString());");
                                }

                                return propCases.ToString();
                            }))()}}
                    });
        """;
    }
}
